
const medicinesSeed = [
    {
      "name": "Paracetamol",
      "unit": "mg",
      "indications": "Alivio del dolor y fiebre",
      "contraindications": "No utilizar en caso de alergia al paracetamol",
      "description": "Analgésico y antipirético",
      "content": 500,
      "type": "Analgésico",
    },
    {
      "name": "Amoxicilina",
      "unit": "mg",
      "indications": "Tratamiento de infecciones bacterianas",
      "contraindications": "No utilizar en caso de alergia a la amoxicilina",
      "description": "Antibiótico de amplio espectro",
      "content": 250,
      "type": "Antibiótico",
    },
    {
      "name": "Ibuprofeno",
      "unit": "mg",
      "indications": "Alivio del dolor y reducción de la inflamación",
      "contraindications": "No utilizar en caso de úlceras estomacales",
      "description": "Antiinflamatorio no esteroideo",
      "content": 200,
      "type": "Antiinflamatorio",
    },
    {
        "name": "Aspirina",
        "unit": "mg",
        "indications": "Alivio del dolor y reducción de la fiebre",
        "contraindications": "No utilizar en caso de úlceras gástricas",
        "description": "Analgésico y antiinflamatorio",
        "content": 325,
        "type": "Analgésico",
      },
      {
        "name": "Loratadina",
        "unit": "mg",
        "indications": "Alivio de los síntomas de la alergia",
        "contraindications": "No utilizar en niños menores de 2 años",
        "description": "Antihistamínico",
        "content": 10,
        "type": "Antialérgico",
      },
      {
        "name": "Ciprofloxacino",
        "unit": "mg",
        "indications": "Tratamiento de infecciones bacterianas",
        "contraindications": "No utilizar en caso de alergia a las quinolonas",
        "description": "Antibiótico de amplio espectro",
        "content": 500,
        "type": "Antibiótico",
      },
      {
        "name": "Diazepam",
        "unit": "mg",
        "indications": "Alivio de la ansiedad y espasmos musculares",
        "contraindications": "No utilizar en caso de glaucoma",
        "description": "Ansiolítico y relajante muscular",
        "content": 10,
        "type": "Psicotrópico",
      },
      {
        "name": "Sertralina",
        "unit": "mg",
        "indications": "Tratamiento de la depresión y trastornos de ansiedad",
        "contraindications": "No utilizar con inhibidores de la monoaminooxidasa (IMAO)",
        "description": "Antidepresivo",
        "content": 50,
        "type": "Antidepresivo",
      },
      {
        "name": "Ranitidina",
        "unit": "mg",
        "indications": "Tratamiento de la acidez estomacal y úlceras pépticas",
        "contraindications": "No utilizar en caso de alergia a la ranitidina",
        "description": "Antagonista del receptor H2",
        "content": 150,
        "type": "Antiácido",
      },
      {
        "name": "Metformina",
        "unit": "mg",
        "indications": "Tratamiento de la diabetes tipo 2",
        "contraindications": "No utilizar en caso de insuficiencia renal",
        "description": "Antidiabético oral",
        "content": 850,
        "type": "Antidiabético",
      },
      {
        "name": "Atorvastatina",
        "unit": "mg",
        "indications": "Reducción del colesterol",
        "contraindications": "No utilizar en caso de enfermedad hepática",
        "description": "Inhibidor de la HMG-CoA reductasa",
        "content": 20,
        "type": "Hipolipemiante",
      },
      {
        "name": "Clonazepam",
        "unit": "mg",
        "indications": "Tratamiento de trastornos de ansiedad y convulsiones",
        "contraindications": "No utilizar en caso de glaucoma de ángulo cerrado",
        "description": "Benzodiazepina ansiolítica",
        "content": 0.5,
        "type": "Ansiolítico",
      },
      {
        "name": "Montelukast",
        "unit": "mg",
        "indications": "Prevención y tratamiento del asma",
        "contraindications": "No utilizar en caso de alergia al montelukast",
        "description": "Antileucotrieno",
        "content": 10,
        "type": "Antiinflamatorio",
      },
      {
        "name": "Warfarina",
        "unit": "mg",
        "indications": "Anticoagulante para prevenir la formación de coágulos sanguíneos",
        "contraindications": "Evitar en pacientes con hemorragias activas",
        "description": "Anticoagulante oral",
        "content": 2,
        "type": "Anticoagulante",
      },
      {
        "name": "Levofloxacino",
        "unit": "mg",
        "indications": "Tratamiento de infecciones bacterianas del tracto respiratorio",
        "contraindications": "No utilizar en menores de 18 años",
        "description": "Antibiótico fluoroquinolona",
        "content": 500,
        "type": "Antibiótico",
      },
      {
        "name": "Escitalopram",
        "unit": "mg",
        "indications": "Tratamiento de la depresión y trastornos de ansiedad",
        "contraindications": "No utilizar con inhibidores de la monoaminooxidasa (IMAO)",
        "description": "Antidepresivo",
        "content": 10,
        "type": "Antidepresivo",
      },
      {
        "name": "Furosemida",
        "unit": "mg",
        "indications": "Tratamiento de la retención de líquidos y la hipertensión",
        "contraindications": "No utilizar en caso de insuficiencia renal aguda",
        "description": "Diurético de asa",
        "content": 40,
        "type": "Diurético",
      },
      {
        "name": "Amlodipino",
        "unit": "mg",
        "indications": "Tratamiento de la hipertensión arterial",
        "contraindications": "Evitar en pacientes con insuficiencia cardíaca aguda",
        "description": "Bloqueador de los canales de calcio",
        "content": 5,
        "type": "Antihipertensivo",
      },
      {
        "name": "Pantoprazol",
        "unit": "mg",
        "indications": "Tratamiento de la acidez estomacal y úlceras pépticas",
        "contraindications": "No utilizar en caso de alergia al pantoprazol",
        "description": "Inhibidor de la bomba de protones",
        "content": 40,
        "type": "Antiácido",
      },
      {
        "name": "Metoprolol",
        "unit": "mg",
        "indications": "Control de la hipertensión y prevención de ataques cardíacos",
        "contraindications": "No utilizar en pacientes con bradicardia",
        "description": "Betabloqueante selectivo",
        "content": 50,
        "type": "Antihipertensivo",
      },
      {
        "name": "Fluoxetina",
        "unit": "mg",
        "indications": "Tratamiento de la depresión y trastornos de ansiedad",
        "contraindications": "No utilizar con inhibidores de la monoaminooxidasa (IMAO)",
        "description": "Antidepresivo",
        "content": 20,
        "type": "Antidepresivo",
      },
      {
        "name": "Cetirizina",
        "unit": "mg",
        "indications": "Alivio de los síntomas de la alergia",
        "contraindications": "No utilizar en niños menores de 2 años",
        "description": "Antihistamínico",
        "content": 10,
        "type": "Antialérgico",
      },
      {
        "name": "Losartán",
        "unit": "mg",
        "indications": "Tratamiento de la hipertensión arterial",
        "contraindications": "Evitar en mujeres embarazadas",
        "description": "Antagonista de los receptores de angiotensina II",
        "content": 50,
        "type": "Antihipertensivo",
      },
      {
        "name": "Dexametasona",
        "unit": "mg",
        "indications": "Tratamiento de la inflamación y reacciones alérgicas",
        "contraindications": "Evitar en infecciones fúngicas sistémicas",
        "description": "Corticoide",
        "content": 4,
        "type": "Antiinflamatorio",
      },
      {
        "name": "Risperidona",
        "unit": "mg",
        "indications": "Tratamiento de la esquizofrenia y trastorno bipolar",
        "contraindications": "No utilizar en pacientes con demencia",
        "description": "Antipsicótico",
        "content": 2,
        "type": "Psicotrópico",
      },
      {
        "name": "Duloxetina",
        "unit": "mg",
        "indications": "Tratamiento de la depresión y trastorno de ansiedad generalizada",
        "contraindications": "Evitar en pacientes con insuficiencia hepática",
        "description": "Inhibidor de la recaptación de serotonina y norepinefrina",
        "content": 30,
        "type": "Antidepresivo",
      },
      {
        "name": "Hidroclorotiazida",
        "unit": "mg",
        "indications": "Tratamiento de la hipertensión y edema",
        "contraindications": "Evitar en pacientes con insuficiencia renal severa",
        "description": "Diurético tiazídico",
        "content": 25,
        "type": "Diurético",
      },
      {
        "name": "Acetaminofén",
        "unit": "mg",
        "indications": "Alivio del dolor y reducción de la fiebre",
        "contraindications": "Evitar consumo excesivo y en pacientes con enfermedad hepática",
        "description": "Analgésico y antipirético",
        "content": 500,
        "type": "Analgésico",
      },
      {
        "name": "Budesonida",
        "unit": "mcg",
        "indications": "Tratamiento del asma y enfermedades pulmonares obstructivas crónicas",
        "contraindications": "No utilizar en casos agudos de broncoespasmo",
        "description": "Corticoide inhalado",
        "content": 100,
        "type": "Antiinflamatorio",
      },
      {
        "name": "Carvedilol",
        "unit": "mg",
        "indications": "Tratamiento de la insuficiencia cardíaca y la hipertensión",
        "contraindications": "Evitar en pacientes con bloqueo cardíaco severo",
        "description": "Betabloqueante no selectivo",
        "content": 25,
        "type": "Antihipertensivo",
      },
      {
        "name": "Esomeprazol",
        "unit": "mg",
        "indications": "Tratamiento de la acidez estomacal y úlceras pépticas",
        "contraindications": "No utilizar en casos de alergia al esomeprazol",
        "description": "Inhibidor de la bomba de protones",
        "content": 40,
        "type": "Antiácido",
      },
      {
        "name": "Mometasona",
        "unit": "mcg",
        "indications": "Tratamiento de enfermedades inflamatorias de la piel",
        "contraindications": "No utilizar en infecciones cutáneas virales",
        "description": "Corticoide tópico",
        "content": 0.1,
        "type": "Dermatológico",
      },
      {
        "name": "Jarabe para la Tos",
        "unit": "ml",
        "indications": "Alivio de la tos y la congestión",
        "contraindications": "No utilizar en niños menores de 2 años",
        "description": "Expectorante y descongestionante",
        "content": 150,
        "type": "Antitusivo",
      },
      {
        "name": "Solución Oral de Hierro",
        "unit": "ml",
        "indications": "Suplemento de hierro para tratar la anemia",
        "contraindications": "Evitar en casos de sobrecarga de hierro",
        "description": "Suplemento mineral",
        "content": 200,
        "type": "Suplemento",
      },
      {
        "name": "Gotas Oftálmicas Lubricantes",
        "unit": "ml",
        "indications": "Alivio de la sequedad ocular",
        "contraindications": "No utilizar en caso de glaucoma",
        "description": "Lubricante ocular",
        "content": 15,
        "type": "Oftálmico",
      },
      {
        "name": "Solución Oral de Paracetamol Infantil",
        "unit": "ml",
        "indications": "Alivio del dolor y la fiebre en niños",
        "contraindications": "No utilizar en caso de alergia al paracetamol",
        "description": "Analgésico y antipirético",
        "content": 120,
        "type": "Pediatría",
      },
      {
        "name": "Enjuague Bucal Antiséptico",
        "unit": "ml",
        "indications": "Prevención de infecciones bucales",
        "contraindications": "Evitar en niños menores de 6 años",
        "description": "Antiséptico bucal",
        "content": 250,
        "type": "Dental",
      },
      {
        "name": "Solución Oral de Ibuprofeno",
        "unit": "ml",
        "indications": "Alivio del dolor y reducción de la inflamación",
        "contraindications": "Evitar en pacientes con úlceras estomacales",
        "description": "Antiinflamatorio no esteroideo",
        "content": 100,
        "type": "Antiinflamatorio",
      },
      {
        "name": "Jarabe Antialérgico",
        "unit": "ml",
        "indications": "Alivio de los síntomas de la alergia",
        "contraindications": "No utilizar en niños menores de 6 años",
        "description": "Antihistamínico",
        "content": 120,
        "type": "Antialérgico",
      },
      {
        "name": "Solución Oral de Lorazepam",
        "unit": "ml",
        "indications": "Tratamiento de la ansiedad y los trastornos del sueño",
        "contraindications": "No utilizar en caso de miastenia gravis",
        "description": "Benzodiazepina ansiolítica",
        "content": 5,
        "type": "Ansiolítico",
      },
      {
        "name": "Colirio Lubricante",
        "unit": "ml",
        "indications": "Alivio de la sequedad ocular",
        "contraindications": "No utilizar en caso de alergia a los componentes",
        "description": "Lubricante ocular",
        "content": 10,
        "type": "Oftálmico",
      },
      {
        "name": "Solución Oral de Ranitidina Infantil",
        "unit": "ml",
        "indications": "Tratamiento de la acidez estomacal en niños",
        "contraindications": "No utilizar en caso de alergia a la ranitidina",
        "description": "Antagonista del receptor H2",
        "content": 75,
        "type": "Pediatría",
      },
      {
        "name": "Solución Oral de Clonazepam Infantil",
        "unit": "ml",
        "indications": "Tratamiento de trastornos de ansiedad en niños",
        "contraindications": "No utilizar en menores de 2 años",
        "description": "Benzodiazepina ansiolítica",
        "content": 2,
        "type": "Pediatría",
      },
      {
        "name": "Solución Oftálmica de Ciclosporina",
        "unit": "ml",
        "indications": "Tratamiento de la sequedad ocular crónica",
        "contraindications": "No utilizar en caso de infecciones oculares activas",
        "description": "Inmunomodulador ocular",
        "content": 10,
        "type": "Oftálmico",
      },
      {
        "name": "Jarabe Expectorante",
        "unit": "ml",
        "indications": "Alivio de la tos y facilitación de la expectoración",
        "contraindications": "Evitar en casos de asma bronquial",
        "description": "Expectorante",
        "content": 180,
        "type": "Antitusivo",
      },
      {
        "name": "Solución Oral de Calcio y Vitamina D",
        "unit": "ml",
        "indications": "Suplemento para la salud ósea",
        "contraindications": "No utilizar en casos de hipercalcemia",
        "description": "Suplemento nutricional",
        "content": 200,
        "type": "Suplemento",
      },
      {
        "name": "Colirio Antibiótico",
        "unit": "ml",
        "indications": "Tratamiento de infecciones oculares bacterianas",
        "contraindications": "No utilizar en casos de alergia a los antibióticos",
        "description": "Antibiótico oftálmico",
        "content": 5,
        "type": "Oftálmico",
      },
      {
        "name": "Solución Oral de Melatonina",
        "unit": "ml",
        "indications": "Suplemento para el tratamiento del insomnio",
        "contraindications": "Evitar en pacientes con trastornos autoinmunitarios",
        "description": "Hormona del sueño",
        "content": 5,
        "type": "Suplemento",
      },
      {
        "name": "Jarabe Antipirético para Niños",
        "unit": "ml",
        "indications": "Alivio de la fiebre en niños",
        "contraindications": "No utilizar en caso de alergia a los componentes",
        "description": "Antipirético",
        "content": 120,
        "type": "Pediatría",
      },
      {
        "name": "Solución Oral de Hidroxizina",
        "unit": "ml",
        "indications": "Tratamiento de la ansiedad y alergias",
        "contraindications": "No utilizar en pacientes con glaucoma",
        "description": "Antihistamínico y ansiolítico",
        "content": 15,
        "type": "Psicotrópico",
      },
      {
        "name": "Gotas Nasales Descongestionantes",
        "unit": "ml",
        "indications": "Alivio de la congestión nasal",
        "contraindications": "No utilizar por más de 3 días consecutivos",
        "description": "Descongestionante nasal",
        "content": 30,
        "type": "Nasal",
      },
      {
        "name": "Solución Oral de Levocetirizina Infantil",
        "unit": "ml",
        "indications": "Alivio de los síntomas alérgicos en niños",
        "contraindications": "No utilizar en niños menores de 2 años",
        "description": "Antihistamínico",
        "content": 60,
        "type": "Pediatría",
      },
      {
        "name": "Comprimidos de Acetaminofén",
        "unit": "mg",
        "indications": "Alivio del dolor y reducción de la fiebre",
        "contraindications": "Evitar consumo excesivo y en pacientes con enfermedad hepática",
        "description": "Analgésico y antipirético",
        "content": 250,
        "type": "Analgésico",
      },
      {
        "name": "Tabletas de Loratadina",
        "unit": "mg",
        "indications": "Alivio de los síntomas alérgicos",
        "contraindications": "No utilizar en niños menores de 6 años",
        "description": "Antihistamínico",
        "content": 10,
        "type": "Antialérgico",
      },
      {
        "name": "Cápsulas de Omeprazol",
        "unit": "mg",
        "indications": "Tratamiento de la acidez estomacal y úlceras pépticas",
        "contraindications": "No utilizar en casos de alergia al omeprazol",
        "description": "Inhibidor de la bomba de protones",
        "content": 20,
        "type": "Antiácido",
      },
      {
        "name": "Pastillas de Clorfeniramina",
        "unit": "mg",
        "indications": "Alivio de los síntomas de la alergia",
        "contraindications": "Evitar en casos de glaucoma",
        "description": "Antihistamínico",
        "content": 4,
        "type": "Antialérgico",
      },
      {
        "name": "Cápsulas de Sertralina",
        "unit": "mg",
        "indications": "Tratamiento de la depresión y trastornos de ansiedad",
        "contraindications": "No utilizar con inhibidores de la monoaminooxidasa (IMAO)",
        "description": "Antidepresivo",
        "content": 50,
        "type": "Antidepresivo",
      },
      {
        "name": "Tabletas de Diazepam",
        "unit": "mg",
        "indications": "Tratamiento de la ansiedad y espasmos musculares",
        "contraindications": "No utilizar en caso de miastenia gravis",
        "description": "Benzodiazepina ansiolítica",
        "content": 5,
        "type": "Ansiolítico",
      },
      {
        "name": "Cápsulas de Metronidazol",
        "unit": "mg",
        "indications": "Tratamiento de infecciones bacterianas y parasitarias",
        "contraindications": "Evitar el consumo de alcohol durante el tratamiento",
        "description": "Antibiótico",
        "content": 500,
        "type": "Antibiótico",
      },
      {
        "name": "Pastillas de Meloxicam",
        "unit": "mg",
        "indications": "Alivio del dolor y la inflamación en enfermedades reumáticas",
        "contraindications": "No utilizar en pacientes con enfermedad renal grave",
        "description": "Antiinflamatorio no esteroideo",
        "content": 15,
        "type": "Antiinflamatorio",
      },
      {
        "name": "Tabletas de Cetirizina",
        "unit": "mg",
        "indications": "Alivio de los síntomas de la alergia",
        "contraindications": "No utilizar en niños menores de 6 años",
        "description": "Antihistamínico",
        "content": 10,
        "type": "Antialérgico",
      },
      {
        "name": "Cápsulas de Ranolazina",
        "unit": "mg",
        "indications": "Tratamiento de la angina de pecho",
        "contraindications": "Evitar en pacientes con insuficiencia hepática grave",
        "description": "Antianginoso",
        "content": 500,
        "type": "Cardiovascular",
      },
      {
        "name": "Tabletas de Escitalopram",
        "unit": "mg",
        "indications": "Tratamiento de la depresión y trastornos de ansiedad",
        "contraindications": "No utilizar con inhibidores de la monoaminooxidasa (IMAO)",
        "description": "Antidepresivo",
        "content": 10,
        "type": "Antidepresivo",
      },
      {
        "name": "Cápsulas de Amoxicilina",
        "unit": "mg",
        "indications": "Tratamiento de infecciones bacterianas",
        "contraindications": "No utilizar en caso de alergia a la amoxicilina",
        "description": "Antibiótico de amplio espectro",
        "content": 500,
        "type": "Antibiótico",
      },
      {
        "name": "Tabletas de Metformina",
        "unit": "mg",
        "indications": "Tratamiento de la diabetes tipo 2",
        "contraindications": "Evitar en casos de insuficiencia renal",
        "description": "Antidiabético oral",
        "content": 850,
        "type": "Antidiabético",
      },
      {
        "name": "Comprimidos de Clopidogrel",
        "unit": "mg",
        "indications": "Prevención de eventos cardiovasculares",
        "contraindications": "Evitar en pacientes con sangrado activo",
        "description": "Antiagregante plaquetario",
        "content": 75,
        "type": "Cardiovascular",
      },
      {
        "name": "Cápsulas de Tamsulosina",
        "unit": "mg",
        "indications": "Tratamiento de la hiperplasia prostática benigna",
        "contraindications": "Evitar en pacientes con hipotensión ortostática",
        "description": "Bloqueador alfa adrenérgico",
        "content": 0.4,
        "type": "Urológico",
      },
      {
        "name": "Aspirina",
        "unit": "mg",
        "indications": "Alivio del dolor y reducción de la fiebre",
        "contraindications": "Evitar en casos de úlceras gástricas",
        "description": "Analgésico y antiinflamatorio",
        "content": 325,
        "type": "Analgésico",
      },
      {
        "name": "Ventolin Inhalador",
        "unit": "mcg",
        "indications": "Alivio de la broncoconstricción en el asma",
        "contraindications": "No utilizar en casos de alergia al salbutamol",
        "description": "Broncodilatador",
        "content": 100,
        "type": "Respiratorio",
      },
      {
        "name": "Paracetamol Jarabe",
        "unit": "ml",
        "indications": "Alivio del dolor y fiebre en niños",
        "contraindications": "No utilizar en caso de insuficiencia hepática",
        "description": "Analgésico y antipirético",
        "content": 120,
        "type": "Pediatría",
      },
      {
        "name": "Simvastatina",
        "unit": "mg",
        "indications": "Reducción del colesterol",
        "contraindications": "Evitar en mujeres embarazadas o lactantes",
        "description": "Estatina",
        "content": 20,
        "type": "Cardiovascular",
      },
      {
        "name": "Ibuprofeno Gel",
        "unit": "g",
        "indications": "Alivio del dolor muscular y articular",
        "contraindications": "Evitar en lesiones cutáneas abiertas",
        "description": "Antiinflamatorio tópico",
        "content": 50,
        "type": "Antiinflamatorio",
      },
      {
        "name": "Amoxicilina-Ácido Clavulánico",
        "unit": "mg",
        "indications": "Tratamiento de infecciones bacterianas",
        "contraindications": "No utilizar en caso de alergia a la penicilina",
        "description": "Antibiótico de amplio espectro",
        "content": 500,
        "type": "Antibiótico",
      },
      {
        "name": "Losartán",
        "unit": "mg",
        "indications": "Tratamiento de la hipertensión arterial",
        "contraindications": "Evitar en mujeres embarazadas",
        "description": "Bloqueador de los receptores de angiotensina II",
        "content": 50,
        "type": "Antihipertensivo",
      },
     
      {
        "name": "Omeprazol",
        "unit": "mg",
        "indications": "Tratamiento de la acidez estomacal y úlceras pépticas",
        "contraindications": "No utilizar en casos de alergia al omeprazol",
        "description": "Inhibidor de la bomba de protones",
        "content": 40,
        "type": "Antiácido",
      },
      {
        "name": "Atorvastatina",
        "unit": "mg",
        "indications": "Reducción del colesterol",
        "contraindications": "Evitar en pacientes con enfermedad hepática",
        "description": "Estatina",
        "content": 20,
        "type": "Cardiovascular",
      },
      {
        "name": "Cetirizina",
        "unit": "mg",
        "indications": "Alivio de los síntomas de la alergia",
        "contraindications": "Evitar en niños menores de 6 años",
        "description": "Antihistamínico",
        "content": 10,
        "type": "Antialérgico",
      },
      {
        "name": "Metformina",
        "unit": "mg",
        "indications": "Tratamiento de la diabetes tipo 2",
        "contraindications": "Evitar en casos de insuficiencia renal",
        "description": "Antidiabético oral",
        "content": 500,
        "type": "Antidiabético",
      },
      {
        "name": "Fluoxetina",
        "unit": "mg",
        "indications": "Tratamiento de la depresión y trastornos de ansiedad",
        "contraindications": "No utilizar con inhibidores de la monoaminooxidasa (IMAO)",
        "description": "Antidepresivo",
        "content": 20,
        "type": "Antidepresivo",
      },
      {
        "name": "Salbutamol Inhalador",
        "unit": "mcg",
        "indications": "Alivio de la broncoconstricción en el asma",
        "contraindications": "No utilizar en casos de alergia al salbutamol",
        "description": "Broncodilatador",
        "content": 200,
        "type": "Respiratorio",
      },
      {
        "name": "Enalapril",
        "unit": "mg",
        "indications": "Tratamiento de la hipertensión arterial",
        "contraindications": "Evitar en casos de insuficiencia renal",
        "description": "Inhibidor de la enzima convertidora de angiotensina (IECA)",
        "content": 10,
        "type": "Antihipertensivo",
      },
      {
        "name": "Clopidogrel",
        "unit": "mg",
        "indications": "Prevención de eventos cardiovasculares",
        "contraindications": "Evitar en pacientes con sangrado activo",
        "description": "Antiagregante plaquetario",
        "content": 75,
        "type": "Cardiovascular",
      },
      {
        "name": "Levocetirizina",
        "unit": "mg",
        "indications": "Alivio de los síntomas alérgicos",
        "contraindications": "No utilizar en niños menores de 6 años",
        "description": "Antihistamínico",
        "content": 5,
        "type": "Antialérgico",
      },
      {
        "name": "Ranitidina",
        "unit": "mg",
        "indications": "Tratamiento de la acidez estomacal",
        "contraindications": "Evitar en casos de alergia a la ranitidina",
        "description": "Antagonista del receptor H2",
        "content": 150,
        "type": "Gastrointestinal",
      },
      {
        "name": "Ciprofloxacino",
        "unit": "mg",
        "indications": "Tratamiento de infecciones bacterianas",
        "contraindications": "Evitar en casos de miastenia gravis",
        "description": "Antibiótico",
        "content": 500,
        "type": "Antibiótico",
      },
      {
        "name": "Dipirona",
        "unit": "mg",
        "indications": "Alivio del dolor y fiebre",
        "contraindications": "No utilizar en casos de agranulocitosis",
        "description": "Analgésico",
        "content": 250,
        "type": "Analgésico",
      },
      {
        "name": "Atenolol",
        "unit": "mg",
        "indications": "Tratamiento de la hipertensión y enfermedades cardíacas",
        "contraindications": "Evitar en casos de asma y bloqueo cardíaco",
        "description": "Betabloqueante",
        "content": 25,
        "type": "Cardiovascular",
      },
      {
        "name": "Montelukast",
        "unit": "mg",
        "indications": "Prevención y tratamiento del asma y las alergias",
        "contraindications": "No utilizar en casos de insuficiencia hepática",
        "description": "Leucotrieno antagonista",
        "content": 10,
        "type": "Respiratorio",
      },
      {
        "name": "Cefuroxima",
        "unit": "mg",
        "indications": "Tratamiento de infecciones bacterianas",
        "contraindications": "No utilizar en caso de alergia a las cefalosporinas",
        "description": "Antibiótico",
        "content": 250,
        "type": "Antibiótico",
      },
      {
        "name": "Naproxeno",
        "unit": "mg",
        "indications": "Alivio del dolor y la inflamación en enfermedades reumáticas",
        "contraindications": "Evitar en casos de úlceras gástricas",
        "description": "Antiinflamatorio no esteroideo",
        "content": 500,
        "type": "Antiinflamatorio",
      },
      {
        "name": "Metoclopramida",
        "unit": "mg",
        "indications": "Tratamiento de náuseas y vómitos",
        "contraindications": "Evitar en casos de obstrucción intestinal",
        "description": "Antagonista del receptor de dopamina",
        "content": 10,
        "type": "Gastrointestinal",
      },
      {
        "name": "Hidroclorotiazida",
        "unit": "mg",
        "indications": "Diurético para el tratamiento de la hipertensión",
        "contraindications": "Evitar en casos de insuficiencia renal",
        "description": "Tiazida",
        "content": 12.5,
        "type": "Diurético",
      },
      {
        "name": "Venlafaxina",
        "unit": "mg",
        "indications": "Tratamiento de la depresión y trastornos de ansiedad",
        "contraindications": "No utilizar con inhibidores de la monoaminooxidasa (IMAO)",
        "description": "Antidepresivo",
        "content": 75,
        "type": "Antidepresivo",
      },
      {
        "name": "Pantoprazol",
        "unit": "mg",
        "indications": "Tratamiento de la acidez estomacal y úlceras pépticas",
        "contraindications": "No utilizar en casos de alergia al pantoprazol",
        "description": "Inhibidor de la bomba de protones",
        "content": 40,
        "type": "Antiácido",
      },
      {
        "name": "Candesartán",
        "unit": "mg",
        "indications": "Tratamiento de la hipertensión y enfermedades cardíacas",
        "contraindications": "Evitar en casos de embarazo",
        "description": "Bloqueador de los receptores de angiotensina II",
        "content": 16,
        "type": "Cardiovascular",
      },
      {
        "name": "Clotrimazol Crema",
        "unit": "g",
        "indications": "Tratamiento de infecciones por hongos en la piel",
        "contraindications": "Evitar en casos de alergia al clotrimazol",
        "description": "Antifúngico",
        "content": 15,
        "type": "Dermatológico",
      },
      {
        "name": "Tramadol",
        "unit": "mg",
        "indications": "Alivio moderado a severo del dolor",
        "contraindications": "Evitar en casos de hipersensibilidad al tramadol",
        "description": "Analgésico opioide",
        "content": 50,
        "type": "Analgésico",
      }
  ]
  
module.exports = { medicinesSeed };